#!/bin/sh
#
# これはホストOS用です
# ターゲットOSの環境を使ってPDFのビルドを行います
#
docker run --rm --entrypoint="./.makedoc" \
    -v $(pwd):/data \
    -v $(pwd)/../rules:/rules \
    -v $(pwd)/../appendix:/appendix \
    -v $(pwd)/../qas:/qas \
    -v $(pwd)/../src:/images \
    -it ordg "$@"
