from: markdown+fenced_divs+lists_without_preceding_blankline
pdf-engine: lualatex
toc: true
toc-depth: 2
# lot: true
template: ./templates/default.tex
include-in-header:
    - ./headers/dotline.tex
    - ./headers/image.tex
variables:
    lang: ja
    luatexjapresetoptions: fonts-noto-cjk
    colorlinks: true
    linkcolor: blue
    urlcolor: red
    toccolor: blue
metadata:
    documentclass: ltjsarticle
    classoption: twoside
    geometry: a4paper, margin=20mm
    title: ディスクゴルフ公式規則
    version: 2025年版
    author: Professional Disc Golf Association
    copyright: The original copyright of this book is reserved by PDGA®.
    publisher: 静岡県ディスクゴルフ協会
    contact: jpdga.shizuoka@gmail.com
    revisions:
    - revision: 2025年版
      date: 2024年12月
